baseURL: https://example.com
languageCode: en-us
title: Hugo
theme: "hugo-theme-mini"

# for exampleSite only, you may need to delete the line: `themesDir: ../../` 

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

googleAnalytics: your-google-analytics-id
disqusShortname: your-disqus-shortname

# Hugo Configure Markup
# see: https://gohugo.io/getting-started/configuration-markup#highlight
markup:
  highlight:
    guessSyntax: true
    style: emacs


# Social links in footer, support github,twitter,stackoverflow,facebook
social:
  # e.g.
  github: your-github-link
  twitter: your-github-link
  stackoverflow: your-github-link
  # facebook: your-facebook-link

math: true

# Site parameters
params:
  # Site Author
  author: Author
  # Author biography
  bio: Software Engineer
  # Site Description, used in HTML meat
  description: My Blog
  enableRSS: true
  # To enable comments, you may need to set `disqusShortname`
  enableComments: true
  # To enable comments, you may need to set `googleAnalytics`
  enableGoogleAnalytics: true

  # Optional
  home: 'Home' # Default: Home
  about: 'About' # Default: About
  archive: 'Archive' # Default: Archive
  tags: 'Tags' # Default: Tags
  subscribe: '' # Default: Subscribe
  olderPosts: '' # Default: Older Posts
  newerPosts: '' # Default: Newer Posts
  copyright: '© Copyright 2021 ❤️ Ryan Teo' # Default: © Copyright 2021 ❤️ author
  title404: '404 - Page Not Found' # Default: 404 - Page Not Found
  subtitle404: 'The content you\'re looking for doesn\'t seem to exist.' # Default: The content you're looking for doesn't seem to exist.
  readMore: 'Read More' # Default: Read More

  # Extra links in navigation
  links:
    # e.g.
    # - name: Project
    #   path: /project
