---
title: Responsible Citizenship in the 2003 SARS Outbreak
author: Ryan Teo
date: '2018-11-01'
slug: responsible-citizenship-in-the-2003-sars-outbreak
categories: []
tags:
  - health policy
bibliography: index.bib
link-citations: true
description: "I wrote this paper for a writing class on citizenship and discourse. I enjoyed exploring the humanistic side of epidemics and disease control, which is not something I get to think about often."
---

# Introduction
Singapore’s management of the 2003 SARS epidemic was heralded as an exemplary model of outbreak management. This was achieved through sound government policies bolstered by strong public cooperation to act ‘responsibly’. This paper aims to examine the discursive strategies employed by the government in creating a narrative surrounding SARS, and the role this narrative played in constructing what constitutes ‘socially responsible’ behaviour and consequently, ‘responsible citizenship’.

Existing literature on SARS management in Singapore provides valuable insights on the rhetorical practices employed by the government in constructing the SARS narrative. Scholars have highlighted how war rhetoric [@ibrahim_sars_2007] and appeals to Confucian ideals [@weber_triumph_2008] featured prominently in the government’s public communication efforts. These form crucial story elements in the SARS narrative that this paper will evaluate.

This paper will adopt Fisher’s narrative paradigm [-@fisher_narration_1984] by evaluating the coherence and fidelity of the SARS narrative in relation to its effectiveness in constructing ‘responsible citizenship’. Essential story elements will be distilled from speeches by key government officials, which were chosen as they were the primary communication methods used by the government to address the public [@menon_sars_2006].

This paper contends that the success of the SARS narrative in mobilising ‘responsible citizenship’ can be attributed to its alignment with the wider survivalist metanarrative of Singapore, which is shaped by strong public trust in the government and a fear of penalties. 

# Literature Review

The analysis of epidemic narratives is not unprecedented in existing literature. The poor management of SARS in China was attributed by scholars to a lack of ‘moral veracity’ and ‘narrative fidelity’ in the Chinese government’s narrative, citing examples of the government withholding critical information about SARS [@bowen_narratives_2007]. However, Singapore has not yet been a subject of such narrative analysis.
The texts that do discuss Singapore’s SARS management surface important rhetorical devices utilised by the government in mobilizing the public. These include the use of war rhetoric [@ibrahim_sars_2007] and Confucian values [@weber_triumph_2008]. I opine that these form the essential story elements through which the SARS narrative is constructed, and that this narrative can be evaluated with regards to Fisher’s [-@fisher_narration_1984] criteria of coherence and fidelity. 

To encourage the public to practice socially responsible behaviour, the SARS narrative had to impart knowledge on SARS. However, post-outbreak studies showed that Singaporeans generally possessed a low level of knowledge about SARS but instead displayed a high level of trust in the government [@deurenberg-yap_singaporean_2005]. This corroborates with Fisher’s narrative theory, which emphasised that people are less convinced by empirical evidence than they are by stories that ‘reassure’ them, which was initiated through extensive campaigns [@menon_sars_2006]. Thus, public trust stands out as an additional influence over Singaporeans’ decision to behave responsibly.

Existing literature portrays Singapore’s mitigation strategy as virtually successful. However, SARS policies experienced varied degrees of success. The enactment of Home Quarantine Orders (HQOs) was a controversial policy that was not completely supported by citizens, a significant number of whom violated their quarantine [@ding_singapores_2013]. This shows that not everybody subscribed to a common understanding of ‘social responsibility’, potentially highlighting flaws in the SARS narrative. The government’s efforts to convince this group of people otherwise through harsh penalties also surface another factor that shaped ‘responsible behaviour’. This fear of penalties can also be discursively constructed. 

Scholars have also framed the entire SARS episode in the wider survivalist metanarrative largely characterised as a ‘perennial crisis mentality’, which is often used to justify policy choices by invoking Singapore’s vulnerability to global threats [@you_singapore_1984]. As a young nation, Singapore’s government relied heavily on public trust instilled from the successful management of past crises such as the 1997 Asian Financial Crisis to ensure cooperation [@weber_triumph_2008]. Additionally, punishments have long been part of the wider metanarrative in Singapore as means ‘to inculcate particular values and patterns of behaviour’ [@wilkinson_social_1988]. These socio-political phenomena can also be interpreted as discursive actions that show the government implicitly capitalising on a narrative of political control in order to influence public behaviour. Singapore’s survivalist metanarrative can therefore be said to be shaped by both public trust and penalties. It is fitting that the survivalist discourse frames the SARS narrative since the outbreak represents an instance of a threat to Singapore’s survival, to which the government responds by propagating social responsibility.

# Critical Approach

The narrative approach of studying crises is an application of Fisher’s narrative paradigm, which theorizes that for narratives to be effective, they should possess coherence and fidelity. In other words, narratives should be probable, internally consistent, and fit into the observer's prior understanding of the issue at hand respectively. Since narratives allow for coordinated activities to help society manage risks collectively [@douglas_active_2013], it would be appropriate to study how the government discursively created a narrative to coordinate and convince citizens to act in accordance with social responsibilities that may sometimes be disruptive to their personal lives. 

The scope of analysis will cover public speeches made by the Prime Minster (PM), Deputy Prime Minister (DPM) and the Minister for Health. These speeches span the time period starting with the first local case of SARS to after Singapore has been declared SARS-free and can show the variety of discursive practices employed to encourage social responsibility. 

This paper will apply the narrative approach by distilling essential story elements in the SARS narrative and examining how they construct ideal traits of ‘responsible citizenship’. The coherence and fidelity of the SARS narrative will also be evaluated, and the narrative itself will also be framed within the wider Singapore survivalist metanarrative.

# The SARS Narrative of ‘Social Responsibility’

The government effectively mobilised Singaporeans to rally together and follow government directives by propagating a narrative in which ‘responsible’ citizens are expected to follow orders and place societal needs above their own. Examples of government-directed ‘social responsibilities’ that citizens are expected to follow include observing personal hygiene, obeying HQOs, and carrying on with their lives as per normal. I argue that the narrative is driven largely by war rhetoric and appeals to Confucian ideals. 

The SARS narrative was a call to action that was driven by war rhetoric. Most of the speeches analysed in this paper portrayed SARS as an invasive threat that required a coordinated ‘defence’ strategy by the government and all Singaporeans.

> [Society] is the most critical battlefront. If we lose this front, we lose all the other fronts, and lose the war - DPM Lee Hsien Loong [@lee_sars_2003]

> Every Singaporean is a soldier in the fight against SARS. We armed every household with a thermometer. That's a weapon. We involved them in this fight against a common enemy - PM Goh Chok Tong [@zubaidah_pm_2003]

The excerpts above rely on symbolism in the narrative to portray the SARS virus as an ‘enemy’ that must be defeated, with war as a signifier to mobilise Singaporeans to take necessary precautions. The war metaphor also discursively constructed the ideal of ‘responsible citizens’ as soldiers in the fight against SARS, emphasising that every citizen has a duty to ‘follow orders’ or obey government directives. In this sense, militarisation was crucial in ensuring the effectiveness and efficiency of the government’s SARS mitigation policies.

> The SARS narrative also featured appeals for citizens to act in accordance with Confucian values that encourage placing society above self [@tan_our_2012].

> Singaporeans should look out for one another … [and] play their part with higher social discipline and social responsibility … [then] we can contain the disease [@lim_coping_2003].

The excerpts above surface appeals to Confucian moral values through an explicit call to action. The very phrase ‘social responsibility’ used by the government reveals an implicit reminder of one of Singapore’s “Shared Values”  of ‘nation before community and society above self’, by implying that citizens have a responsibility not just to themselves, but to society at large that may have greater importance. Thus, a responsible citizen in the SARS narrative is one who acts in accordance with social good, or for the benefit of the community.

The rhetorical practices of war rhetoric and appeals to Confucian values largely complement each other in their portrayal of SARS. Both practices portray SARS as a ‘mysterious’, ‘uncontrollable’ threat  [@ibrahim_sars_2007] that strikes directly at the “Shared Values” framework [@weber_triumph_2008] that needed to be defused. The use of both rhetorical practices creates a holistic means of persuasion that appeal to the wide range of emotions felt by the audience. War rhetoric plays on fear and anxiety through metaphorical imagery of battle and invasion while appeals to Confucian values elicit feelings of empathy for others. Together they encapsulate the complex emotions felt by an Singaporeans at the time and weave a coherent and relatable narrative that provides reason for them to practice their social responsibilities as a service to the country as well as to each other. Hence, the SARS narrative on its own was largely coherent. 

# The Wider Metanarrative of ‘Survivalism’

Fisher asserts that apart from coherence, effective narratives need to fit well into the observer’s prior understanding. An evaluation of the fidelity of the SARS narrative would require an examination of how well it aligns with the Singapore’s survivalist metanarrative, which is discursively constructed by socio-political conditions.

The SARS narrative would not have thrived without the strong public trust Singaporeans placed in their government. This public trust, already deeply entrenched in Singaporeans, was heightened during the outbreak as the government actively reminded Singaporeans of their success in dealing with past crises of similar severity.

>	We can overcome this latest crisis if we work together, as we have done in previous crises - PM Goh Chok Tong [@goh_fighting_2003].

Apart from the excerpt above, PM Goh also expressed 'tremendous confidence' in Singaporeans in dealing with SARS ‘given how they overcame the troubles of the past few years’ [@zubaidah_pm_2003]. PM Goh conducted his speech over lunch with media correspondents at the Rendezvous Restaurant to show Singaporeans that they need not be afraid to be in public places [@weber_triumph_2008]. This use of text and symbolic action to appeal to authority and history proved to be successful, as most Singaporeans trusted the government enough to adhere to directives despite having limited knowledge of SARS [@deurenberg-yap_singaporean_2005]. It is reasonable to argue that without such strong confidence, Singaporeans would not have been inclined to behave responsibly, especially since mistrust in the government was a significant factor in the failure of China and Hong Kong’s SARS mitigation efforts [@bowen_narratives_2007; @lee_how_2009]. Thus, the SARS narrative thrived because it aligned with the metanarrative built on public trust.

However, the SARS narrative was not completely effective in mobilising every Singaporean to act responsibly, as evidenced by a minority who defaulted on their HQOs. Such actions placed other people at risk of exposure to SARS and showed that the SARS narrative were some who did not subscribe to the government’s notion of social responsibility. In response, the government publicly called out this irresponsible behaviour and increased the severity of punishments for HQO violators, as DPM Lee says:

> While most people on HQOs have complied and cooperated, a minority are recalcitrant and incorrigible [@lee_sars_2003]

In the quote above, DPM Lee lambasts those who defaulted on HQOs as irresponsible, and later in the speech he proceeds to announce the doubling of penalties for violating the Infectious Disease Act. The government’s decision to employ a more forceful means of persuasion for those deemed ‘socially irresponsible’ reveals the limits of how far narratives can go in encouraging responsible behaviour. The SARS narrative fits well within the survivalist metanarrative because it propagates the same message of placing society above self, differing only in its approach. The SARS narrative’s appeal to Confucian values is a soft reminder while penalties are a tougher measure. Thus, where the SARS narrative was less effective, the wider survivalist metanarrative, which was partly driven by penalties, was engaged to encourage social responsibility.

To summarise, the deeply entrenched survivalist metanarrative that reminds Singaporeans of Singapore’s vulnerability to existential threats has instilled strong public trust as well as a fear of penalties in Singaporeans. These conditions enhanced the fidelity of the SARS narrative, which was also bolstered by strong coherence, thereby leading to an overall effectiveness in the narrative’s construction of ‘responsible citizenship’.

# Conclusion

In conclusion, the SARS narrative alone cannot be attributed to shaping ‘social responsibility’ during the SARS outbreak. While war rhetoric and appeals to Confucian values helped to mobilise the public, their influence on public behaviour would likely be weaker had they not aligned with the survivalist metanarrative. In other words, public trust and a fear of penalties, which are deeply entrenched socio-political conditions in Singapore that shape the survivalist metanarrative, enabled the SARS narrative to thrive.

This paper has shown that narratives play an important role in influencing public behaviour and that their success is shaped by how well they align with the prevailing metanarrative. The paper has also illustrated how ‘responsible citizenship’ as an ideal is shaped by narratives discursively constructed by the government and wider socio-political conditions.

# References